// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbotkzwtioujmkxwjtan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdib3Rrend0aW91am1reHdqdGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDkxMjIsImV4cCI6MjA2MzI4NTEyMn0.fBDsTYaQQ0-vdHK-AO6vA9DhL1_f_8M8OUAZr1s8ZfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);